language: node_js
sudo: required
services:
    - docker

before_install:
    - docker build -t tomket/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true tomket/react-test npm test

after_success:
    - docker build -t tomket/multi-client ./client
    - docker build -t tomket/multi-nginx ./nginx
    - docker build -t tomket/multi-server ./server
    - docker build -t tomket/multi-worker ./worker

    # Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # Take those images and push them to docker hub
    - docker push tomket/multi-client 
    - docker push tomket/multi-nginx
    - docker push tomket/multi-server
    - docker push tomket/multi-worker

deploy:
    edge: true
    provider: elasticbeanstalk
    region: eu-west-2
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-eu-west-2-274372526749
    bucket_path: docker-multi
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY